package model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Pikachu on 8/9/15.
 */
@Entity
@Table(name = "user")
public class User {

    // Entity's fields (private)

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    private String firstName;

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    private String lastName;

    public int getUserType() {
        return userType;
    }

    public void setUserType(int userType) {
        this.userType = userType;
    }

    private int userType;

    public User() { }

    public User(String firstName, String lastName, int userType) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.userType = userType;
    }

    public User(long id) {
        this.id = id;
    }


}

